export const helpTopics = [
  { id: "translate", title: "How do I change the review language?", keywords: "translate translation language languages read understand dropdown", answer: "Open a review in Reviews. Under ‘Read this review in’, open the dropdown, search for a language and select it. Then use the translation button. Cached translations work offline; a new translation needs your connected NLLB laptop. Selecting a language does not translate automatically.", link: "/reviews", action: "Open reviews" },
  { id: "reply", title: "How do I respond to a review?", keywords: "respond response reply write writing customer approve approval post publish send", answer: "Open an unanswered review. Choose your writing language and the customer’s language, write your own reply, then translate if needed. Read the result before approving it. Approval saves a local reply; Lauda does not post it to Yelp or another review site. Copy the approved reply to the original platform yourself.", link: "/reviews", action: "Find a review" },
  { id: "draft", title: "Can I save a reply for later?", keywords: "draft save saved later unfinished lost", answer: "Use ‘Save draft’ in the review response section. Your text and language choices stay on this device. Open the same review to continue. Changing the draft clears its previous translation so you can check the new version before approval.", link: "/reviews", action: "Open review queue" },
  { id: "queue", title: "Where are the unanswered reviews?", keywords: "unanswered new queue filter search answered reviews review", answer: "Open Reviews and select New to find reviews that still need a reply. Search by visitor name or review text, or use the language filter. Answered contains sample replies; Approved contains replies you approved locally. Demo reviews are examples, not live customer submissions.", link: "/reviews", action: "Open reviews" },
  { id: "bookings", title: "How do I manage bookings?", keywords: "booking bookings reservation reservations guest guests schedule calendar capacity tour", answer: "Open Bookings to view the schedule and pending requests. Open a booking to inspect its guest details and status. Check the date, time and capacity before confirming. Bookings are stored locally; no external booking service is connected.", link: "/bookings", action: "Open bookings" },
  { id: "insights", title: "What can I see in Insights?", keywords: "insight insights idea ideas recommendations feedback evidence improve analysis", answer: "Open Insights to see your review count, average star rating and reviews awaiting a reply. The business overview is a placeholder: the AI summary and score will be added later. Use View reviews to read and respond to individual reviews.", link: "/insights", action: "Explore insights" },
  { id: "profile", title: "Where do I edit my business?", keywords: "profile business name price hours settings setup edit change details", answer: "Tap the sliders icon at the top right to open Business Profile. Update the business details and save your changes. Your profile belongs to this device; there is no login or cloud account required to use Lauda.", link: "/profile", action: "Open business profile" },
  { id: "offline", title: "What works without internet?", keywords: "offline internet wifi network connection airplane storage local", answer: "Your saved profile, reviews, bookings, drafts, cached translations and this Help guide work locally. New NLLB translations run on the connected laptop and need a local network connection, even if the internet is disconnected. The model is not installed inside Expo Go. Keep the laptop running and use the same Wi-Fi when translating new text.", link: "/offline", action: "Check offline status" },
  { id: "model", title: "Why is translation unavailable?", keywords: "nllb model unavailable error failed pairing server laptop connect token", answer: "Open Offline & AI and check the laptop address and pairing code. Keep the translation service running and put your phone and laptop on the same local network. Test the connection there, then return to your review. If the laptop was restarted, its pairing code may have changed. Drafts remain on your device when translation fails.", link: "/offline", action: "Check translation connection" },
] as const;
export type HelpTopic = typeof helpTopics[number];
const normalize = (text: string) => text.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu, " ").split(/\s+/).filter(Boolean);
const stopwords = new Set("how do i a an the to my can where is it in on for of me this that what we use app lauda please".split(" "));
export function answerAppQuestion(question: string): HelpTopic | null {
  const terms = [...new Set(normalize(question).filter(word => !stopwords.has(word)))];
  if (!terms.length) return null;
  const ranked = helpTopics.map(topic => ({ topic, score: terms.reduce((score, term) => score + (normalize(topic.keywords).includes(term) ? 2 : 0) + (normalize(topic.title).includes(term) ? 1 : 0), 0) })).sort((a,b) => b.score-a.score);
  return ranked[0].score >= 2 ? ranked[0].topic : null;
}
