import type { Review } from "../data/types.ts";
export const ideaLibrary = [
  { id: "arrival", theme: "directions", title: "A smoother arrival", summary: "A tiny change with a big first impression.", plan: "Send a photo of the final turn, a walking map from the bus stop, and an arrival checklist before each booking.", measure: "Ask the next 10 groups whether they found the farm without calling.", effort: "Quick win", icon: "navigate-outline" },
  { id: "tasting", theme: "tasting", title: "The tasting flight", summary: "Turn the favourite moment into its own experience.", plan: "Pilot a small-group tasting of three coffees, with a flavour card visitors can take home.", measure: "Invite five past visitors and test willingness to book before buying equipment.", effort: "New offering", icon: "cafe-outline" },
  { id: "roast", theme: "learning", title: "Roast with the grower", summary: "Make learning something visitors can do.", plan: "Trial a longer hands-on roasting class with time for questions and a take-home sample.", measure: "Compare interest in the class with the standard tour over two weeks.", effort: "New offering", icon: "flame-outline" },
  { id: "family", theme: "family", title: "Little explorers", summary: "A visit designed around curious children.", plan: "Test a shorter family route with a coffee-plant scavenger hunt and a quiet rest stop.", measure: "Ask three families to trial it and review the route together.", effort: "Small pilot", icon: "people-outline" },
  { id: "access", theme: "accessibility", title: "Know before you go", summary: "Replace uncertainty with verified access details.", plan: "Document steps, path surfaces, toilets and seating with photos; ask visitors what accommodations they need.", measure: "Review the information with an accessibility advisor and two visitors.", effort: "Quick win", icon: "accessibility-outline" },
  { id: "pace", theme: "time", title: "More space, less rush", summary: "Let the tour breathe.", plan: "Trial smaller groups and a question break after roasting; communicate the start time clearly.", measure: "Compare feedback on pacing and audibility across the next six tours.", effort: "Small pilot", icon: "time-outline" },
  { id: "sunset", theme: "sunset", title: "Golden-hour coffee", summary: "A new reason to return in the evening.", plan: "Pilot one sunset tasting with a capped group, checking lighting, transport and staff availability first.", measure: "Collect sign-ups before scheduling a second evening.", effort: "New offering", icon: "sunny-outline" },
  { id: "retail", theme: "retail", title: "Take the farm home", summary: "Keep the experience alive after the visit.", plan: "Test a small coffee gift pack with a brewing card and the grower's story.", measure: "Offer a pre-order to ten visitors to test demand without stocking heavily.", effort: "Small pilot", icon: "bag-handle-outline" },
  { id: "sustainability", theme: "sustainability", title: "From soil to cup", summary: "Turn sustainable growing into a practical workshop.", plan: "Try a composting and growing session where guests practise one technique and leave with a simple guide.", measure: "Ask visitors to choose between this workshop and a standard farm walk.", effort: "New offering", icon: "leaf-outline" },
] as const;
export function ideasFor(reviews: Review[]) {
  return ideaLibrary.map(idea => ({ ...idea, evidence: reviews.filter(r => r.theme === idea.theme) })).filter(idea => idea.evidence.length > 0).sort((a,b) => b.evidence.length-a.evidence.length);
}
